### ISSUE TITLE
Update module on LuaRocks

### ISSUE THREAD

**Issue by jirutka** [wahern/lunix#10]
The last version on LuaRocks is pretty old, 20140819-6, but the last on GitHub is 20150923. Could you please upload latest rockspec to LuaRock?

**Comment by jirutka** [comment]
As I see there’s a bunch of changes in the repo since 20150923. More frequent releases would be also very helpful. :)

**Comment by wahern** [comment]
I don't package it. I think daurnimator does. Maybe he's waiting on a release tag. I'll try to get to that soon.

**Comment by daurnimator** [comment]
I do have **a** luarocks package for lunix but @amrhassan has the global/main one.

**Comment by jirutka** [comment]
I’m confused. I can find only one rock named lunix on LuaRocks – https://luarocks.org/search?q=lunix.

**Comment by daurnimator** [comment]
I see two: https://luarocks.org/search?q=lunix&non_root=on

**Comment by jirutka** [comment]
Well, but the second one is not in root manifest, so I can’t use it in my rockspec… or can I?

**Comment by daurnimator** [comment]
Correct: it won't be picked up unless you use/specify my manifest.

We'll should get @amrhassan to either update their rock or transfer the name to me. ping @leafo

**Comment by leafo** [comment]
I'd be glad to transfer, just need confirmation from existing owner

**Comment by daurnimator** [comment]
This was completed.
