### ISSUE TITLE
Use of glibc's internal __libc_enable_secure() restricts from using a source-compatible libc alternative

### ISSUE THREAD

**Issue by amrhassan** [wahern/lunix#3]
Hello,

I'm trying to compile lunix against uClibc for use on an embedded device and because of the usage of this glibc-internal function, lunix is failing to find the symbol __libc_enable_secure() at runtime. Can the more portable function be used instead for that purpose?

Thanks.

**Comment by wahern** [comment]
That symbol is used in unix_issetugid_linux, and only if __GLIBC_PREREQ(2, 1) is true. It already has a fallback. Does uClibc define __GLIBC_PREREQ to something that would evaluate to true? Or maybe you compiled against glibc?

With some tweaks I can compile the module against the new MUSL libc. It doesn't have __libc_enable_secure, either, but I didn't have an issue with that symbol. (The problems were related to a lack of sys/sysctl.h.)

**Comment by amrhassan** [comment]
Yes I am compiling against uClibc and it indeed defines __GLIBC_PREREQ(x,x) to mimic the exact behaviour of glibc because it is created to be source compatible with it. Its internals however are not exactly like glibc and that's why this is happening.

**Comment by wahern** [comment]
On Sun, Mar 01, 2015 at 05:12:47AM -0800, Amr Hassan wrote:
> Yes I am compiling against uClibc and it indeed defines __GLIBC_PREREQ(x,x) to mimic the exact behaviour of glibc because it is created to be source compatible with it. Its internals however are not exactly like glibc and that's why this is happening.
> 

I'm adding autoconf support for feature testing this week, and that should
fix this problem.

**Comment by wahern** [comment]
Can you try building from the "autoconf" branch. You don't need to run ./configure to try it out. The branch also contains a fix to the preprocessor-based feature detection.

I don't have a uclibc environment to test, though. So there may be other problems. If the normal build doesn't work, try running ./bootstrap and then ./configure, which will run autoconf feature detection, which overrides the pre-processor-based feature detection.
